### ISSUE TITLE
incompatible with chef chef 12.16.42

### ISSUE THREAD

**Issue by jlosito** [sous-chefs/php#244]
### Cookbook version
v6.1.1

### Chef-client version
12.16.42

### Platform Details
CentOS 7.6

### Scenario:
I believe there's a transient dependency conflict. Right now the php cookbook is using build-essential >= 5.0, which I believe will install build-essential == 8.2.1, and build-essential has a dependency of seven_zip without pinning the version which will install seven_zip == 3.1.0, but seven_zip == 3.1.0 is only compatible with chef versions >= 13.0, but your README states that the php cookbook works with >= 12.7.

Is there someway we can pin the correct version so that it is compatible with >= 12.7?

![Screen Shot 2019-03-21 at 14 03 17](https://user-images.githubusercontent.com/25142529/54774437-1cd62880-4be2-11e9-86c8-f13b13839560.png)

**Comment by Stromweld** [comment]
since 12.x and soon 13.x are End of Life, Chef 15 comes out in April, the biggest thing I see happening is that the metadata gets bumped up to say minimum chef-client version will need to be 13 or 14. Your best using a wrapper and pinning the versions of the dependencies there.
