### ISSUE TITLE
How can i install php 7.2 on amazonlinux2? 

### ISSUE THREAD

**Issue by tarunjangra** [sous-chefs/php#304]
It is not a bug or feature rather a question. Is there any way i can use amazon-linux-extras to install php 7.2 on amazon linux 2.

**Comment by ramereth** [comment]
Based on what I know, I think that is a little bit outside of the scope of this cookbook. Seems as though you could enable that repo in a wrapper cookbook and then update the packages attributes to install it. Or am I misunderstanding this?

**Comment by tarunjangra** [comment]
yeah, you are right. Doing 'amazon-linux-extras enable php7.2' has solved my problem. 

Thanks
