### ISSUE TITLE
Default recipe pulls in Apache on Ubuntu 20.04

### ISSUE THREAD

**Issue by hrak** [sous-chefs/php#311]
## :ghost: Brief Description

The default recipe pulls in Apache on Ubuntu 20.04 (it doesn't on Ubuntu < 20.04)

The problem can be solved by specifying specific versions for `node['php']['packages']`, similar to what is in `attributes/default.rb` for versions of Ubuntu other that 20.04.

```
default['php']['packages']         = %w(php7.4-cgi php7.4 php7.4-dev php7.4-cli php-pear)
```

## :pancakes: Cookbook version

v8.0.0

## :woman_cook:  Chef-Infra Version

chef 14.15.6

## :tophat: Platform details

Ubuntu 20.04

## Steps To Reproduce

1. converge default recipe
2. `dpkg -l | grep apache`

## :police_car: Expected behavior

Apache not being pulled in as a dep.

**Comment by ramereth** [comment]
@hrak do you feel you could make a PR which addresses this? We'll gladly review and merge it in if it looks good. Thanks!
